### ISSUE TITLE
Problem in launching suyambu - REG

### ISSUE THREAD

**Issue by jagathrajah** [anyms/suyambu#1]
Traceback (most recent call last):
     File "./suyambu", line 5, in <module>
          from libs.core import Suyambu
     File "/home/anon/suyambu/libs/core.py", line 11, in <module>
          from tabulate import tabulate
ImportError: No module named tabulate

**Comment by anyms** [comment]
you have to install all the requirements as it mentioned in the **README.md**

run the the following command in suyambu folder
`sudo pip install -r requirements.txt`

your error is saying that `tabulate` module not installed on your system, you can install modules using pip
`sudo pip install tabulate`

**Comment by jagathrajah** [comment]
Bro what happened bro ?
