### ISSUE TITLE
! could not connect to the backdoor, 

### ISSUE THREAD

**Issue by gnanesh023** [anyms/suyambu#2]
*] please wait... verifying shell...
[!] Following is a handler that pre coded with some basic functionality to handle the payload, type '?' or 'help' to see more.
! could not connect to the backdoor, because shell did not respond

**Comment by anyms** [comment]
Did you generate the payload with your own key? because the error comes if the key validation failed, or the server is too old for the payload. Give me more information to guide you.

**Comment by gnanesh023** [comment]
yes i generated with my own key 
without error
